steps:
  - name: gcr.io/cloud-builders/docker
    args: ['build', '-t', 'asia-south2-docker.pkg.dev/codewithb-453208/bp-repos/gcp-plain-cloudfunction', '--build-arg=JAR_FILE=build/libs/gcp-plain-cloudfunction-1.0-SNAPSHOT-all.jar', '.']
images: ['asia-south2-docker.pkg.dev/codewithb-453208/bp-repos/gcp-plain-cloudfunction']